version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/home/project/image_api"
    links:
      - mongo
      - redis
    command: nodemon

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  redis:
    container_name: redis
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
        - '6379:6379'
    volumes:
      - ./redis-data:/redis-data/data
